version: '3.8'

services:
  redis-cluster-0:
    build:
      context: ./redis
      dockerfile: Dockerfile
    image: redis-cluster-node
    container_name: redis-cluster-0
    environment:
      X_REDIS_PORT: 6379
    ports:
      - 6379:6379

  redis-cluster-1:
    image: redis-cluster-node
    container_name: redis-cluster-1
    environment:
      X_REDIS_PORT: 7001
    ports:
      - 7001:6379

  redis-cluster-2:
    image: redis-cluster-node
    container_name: redis-cluster-2
    environment:
      X_REDIS_PORT: 7002
    ports:
      - 7002:6379

  redis-cluster-3:
    image: redis-cluster-node
    container_name: redis-cluster-3
    environment:
      X_REDIS_PORT: 7003
    ports:
      - 7003:6379

  redis-cluster-4:
    image: redis-cluster-node
    container_name: redis-cluster-4
    environment:
      X_REDIS_PORT: 7004
    ports:
      - 7004:6379

  redis-cluster-5:
    image: redis-cluster-node
    container_name: redis-cluster-5
    environment:
      X_REDIS_PORT: 7005
    ports:
      - 7005:6379

  redis-cluster-6:
    image: redis-cluster-node
    container_name: redis-cluster-6
    environment:
      X_REDIS_PORT: 7006
    ports:
      - 7006:6379
